apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: dbconfig
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: dbconfig
        image: mysql
        name: mysqldb
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: dbpath
      nodeSelector:
        gpu: nvidia
      volumes:
      - name: dbpath
        persistentVolumeClaim:
          claimName: mydbpvc