apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydbpv
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp/mysql
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow