apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydbpvc
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: slow